"""initial

Revision ID: 1e870a4cd909
Revises: 
Create Date: 2021-12-11 21:16:12.716622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e870a4cd909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airport',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('IATACode', sa.Integer(), nullable=True),
    sa.Column('max_plane_number', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=True),
    sa.Column('departure_city', sa.String(length=100), nullable=True),
    sa.Column('arrival_city', sa.String(length=100), nullable=True),
    sa.Column('departure_data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passengers_number', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Integer(), nullable=True),
    sa.Column('crew_number', sa.Integer(), nullable=True),
    sa.Column('airport_id', sa.Integer(), nullable=True),
    sa.Column('plain_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plane',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plane_name', sa.String(length=100), nullable=True),
    sa.Column('max_range', sa.String(length=100), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('max_passenger_number', sa.Integer(), nullable=True),
    sa.Column('tech_chceck_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('passport_number', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('is_github_account', sa.Boolean(), nullable=True),
    sa.Column('confirmed_email', sa.Boolean(), nullable=True),
    sa.Column('confirm_code', sa.String(length=65), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('luggage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('luggage')
    op.drop_table('booking')
    op.drop_table('user')
    op.drop_table('plane')
    op.drop_table('pilot')
    op.drop_table('flight')
    op.drop_table('airport')
    op.drop_table('admin')
    # ### end Alembic commands ###
