"""initial

Revision ID: 71380457f41b
Revises: a88e99a3a588
Create Date: 2022-01-09 17:22:53.396462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71380457f41b'
down_revision = 'a88e99a3a588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('plane_id', sa.Integer(), nullable=True))
    op.drop_column('flight', 'plain_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('plain_id', sa.INTEGER(), nullable=True))
    op.drop_column('flight', 'plane_id')
    # ### end Alembic commands ###
