"""empty message

Revision ID: cbbb6831172b
Revises: f3f50f8186b0
Create Date: 2022-01-23 21:08:29.264038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbb6831172b'
down_revision = 'f3f50f8186b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'flight_id')
    op.add_column('order', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'amount')
    op.add_column('cart', sa.Column('flight_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'cart', 'flight', ['flight_id'], ['flight_id'])
    # ### end Alembic commands ###
