"""empty message

Revision ID: f3f50f8186b0
Revises: 
Create Date: 2022-01-23 20:42:34.957649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f50f8186b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cart', sa.Column('bought', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'flight_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('flight_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'cart', 'flight', ['flight_id'], ['flight_id'])
    op.drop_column('cart', 'bought')
    op.drop_table('order')
    # ### end Alembic commands ###
